config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users
  resources :friends

  root "friends#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
     @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def correct_user
      @friend = current_user.friends.find_by(id: params[:id])
      redirect_to friends_path, notice: "Not authorized to edit"
    end

    
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :first_name, style: "display: block", class: 'form-label' %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, style: "display: block", class: 'form-label'  %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block", class: 'form-label'  %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, style: "display: block", class: 'form-label'  %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: 'btn btn-primary' %> |
  <%= link_to "Back to friends", friends_path, class: 'btn btn-dark' %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in?%>

<h1>My Friends</h1>
<br/>
<div class="table-responsive-sm">
  <table class="table table-striped table-hover">
    <thead class="table-dark">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody class="table-group-divider" >
      <% current_user.friends.each do |friend| %>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= link_to "View", friend, class:'btn btn-dark' %></td>
        </tr>
      <% end %>
      
    </tbody>
  
  </table>
</div>

<%= link_to 'Add friend', new_friend_path, class:"btn btn-secondary"%>

<% else %>

<h1>FriendBook</h1>
<p> Click the links above to start adding friends!</p>

<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class: 'btn btn-primary' %>
</div>

app/views/friends/show.html.erb
<div class="container bg-light">
  <h1><%= @friend.first_name %> <%= @friend.last_name %></h1>
  
  <p><%= @friend.phone %> | <%= @friend.email %></p>

  <div>
    <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-info" %>  | 
    <%= link_to "Back to My Friends", friends_path, class:"btn btn-dark" %>
    <br/><br/><br/>
    <%= button_to "Delete Friend", @friend, method: :delete, class:"btn btn-danger" %>
  </div>
</div>  

app/views/layouts/_alerts.html.erb
<br/>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'FriendBook', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class:"btn btn-link nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Friends', friends_path, class:"btn btn-link nav-link" %>
          </li>
  
          <li class="nav-item">
            <%= link_to 'Update Profile', edit_user_registration_path, class:"btn btn-link nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to("Log Out", destroy_user_session_path, class:"btn btn-link nav-link", method: :delete) %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class:"btn btn-link nav-link" %>
          </li>
  
           <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-link nav-link"%>
          </li>
        <% end %>


      </ul>
      
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FriendsList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_importmap_tags %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    
    <%= render "layouts/header"%>
    <div class="container">
      <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
      <br/>
      <%= yield %>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>